easy_admin:
    site_name: 'Joe'
    design:
        brand_color: '#000000'
    entities:
        # List the entity class name you want to manage
        Art:
            class: 'App\Entity\Art'
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'available' }
                    - { property: 'height' }
                    - { property: 'width' }
                    - { property: 'price', type: 'money', type_options: { currency: 'CAD' } }
                    - { property: 'medium', type: 'choice', type_options: { choices : { 'Oil' : 'Oil', 'Mixte Media' : 'Mix', 'Drawing': 'Drawing' } } }
                    - { property: 'imageFile', type: 'vich_image' }
            list:
                actions: 
                    - { name: 'show', icon: 'search', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }  
                    - { name: 'delete', icon: 'trash', label: false }
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.art_images%', label: 'Images' }
                    - { property: 'title' }
                    - { property: 'medium' }
                    - { property: 'available' }
                    - { property: 'size' }
                    - { property: 'price'}
#        - App\Entity\Category
#        - App\Entity\User
