easy_admin:
    site_name: 'Template'
    design:
        brand_color: '#1ABC9C'
    entities:
        # List the entity class name you want to manage
        Product:
            class: 'App\Entity\Product'
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'imageFile', type: 'vich_image' }
            list:
                actions: 
                    - { name: 'show', icon: 'search', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }  
                    - { name: 'delete', icon: 'trash', label: false }
                fields:
                    - id
                    - { property: 'name'}
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%', label: 'Images' }
#        - App\Entity\Category
#        - App\Entity\User
