vich_uploader:
    db_driver: orm

    mappings:
        art_images:
            uri_prefix: '%app.path.art_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.art_images%'
