core_homepage:
    path: /{_locale}/
    controller:  App\Controller\CoreController::indexWithLocal
    requirements:
      _locale: en|fr 
      
core_homepage_wo_locale:
    path: /
    controller: App\Controller\CoreController::index

app_lucky_number:
    path: /{_locale}/lucky/number
    controller: App\Controller\CoreController::number
    
app_liip_test:
    path: /liip/test
    controller: App\Controller\CoreController::liip